### ISSUE TITLE
Sample choice operator?

### ISSUE THREAD

**Issue by haf** [xyncro/chiron#15]
Another sample I'd like to see in the code base, let's say I have:

``` javascript
{ "entity": 45 }
```

OR

``` javascript
{ "entity": "SEK" }
```

And I want to match based on whether it's a string or a number; how would I do that best in `FromJson`?

**Comment by kolektiv** [comment]
I think those operators are pretty reasonable and non-clashy. I'll try and come up with a suitable location for them!

**Comment by kolektiv** [comment]
I've omitted these from PR #30 for now as they were only used within the lib in the decimal question (which I've reverted for now, see #22). However, I think they do lead on to a good potential set of combinators, so I'm going to create a branch for experimenting with that concept and move them in to there where we can experiment with what a full set of potential combinators for chaining errors/alternatives, etc. through might look like. Would love your input and thoughts @haf!

**Comment by haf** [comment]
Ping me in the PR thread when you've started.
