### ISSUE TITLE
Error in auto-complete for client framework

### ISSUE THREAD

**Issue by haf** [xyncro/chiron#17]
https://bugzilla.xamarin.com/show_bug.cgi?id=29240

Suggested fix: move to a 'full' framework instead.

**Comment by kolektiv** [comment]
Yeah I'm actually fine with that. Originally was quite careful to stick to client frameworks because of the usage in Freya, but we dropped that for Freya too, so I'm happy to go with this.

**Comment by kolektiv** [comment]
Merged in #30.
