### ISSUE TITLE
Dates break on computers that aren't in GMT/UTC.

### ISSUE THREAD

**Issue by haf** [xyncro/chiron#20]
Tests fail in other timezones.

![screen shot 2015-04-20 at 13 38 09](https://cloud.githubusercontent.com/assets/193115/7229310/828de2a0-e762-11e4-87ed-98c155cc6066.png)

**Comment by kolektiv** [comment]
Yeesh, yeah, needs fixing, will certainly merge that change.

**Comment by kolektiv** [comment]
Merged in #30.
