### ISSUE TITLE
decimal serialisation loses accuracy

### ISSUE THREAD

**Issue by haf** [xyncro/chiron#22]
If we serialise decimal, we lose the 128 bit accuracy; better to serialise it to a string by default and parse that string.

**Comment by haf** [comment]
Fixed by https://github.com/xyncro/chiron/pull/18/files#diff-1090e6da10894be536ef99858edf77ccR790

**Comment by kolektiv** [comment]
This one I'm torn on. I can definitely see what you mean, but worry about breaking the very 1-1 mapping between .net and json types (despite the json number type being a horror story). Might sleep on this :)

**Comment by haf** [comment]
For me, if I use decimal I've made a decision that I need the accuracy; otherwise I'd use a 64 bit type; also the PR still allows numeric input (which is what you might expect in API usage terms)...

**Comment by kolektiv** [comment]
Yeah, that's not unreasonable - the allowance for either input is probably
enough to make it sane given a major version bump :)

**Comment by haf** [comment]
I just realised JSON numbers have potentially infinite number of decimals (according to its spec). Let's *not* use string; but instead parse numbers to 128 bits accuracy if we're deserialising to a decimal? http://json.org/

**Comment by kolektiv** [comment]
I'm going to close this and create a new issue (I've reverted the string roundtripping in #30) with a more specific case of parsing to accuracy.
