### ISSUE TITLE
Provide a way to call through reflection

### ISSUE THREAD

**Issue by haf** [xyncro/chiron#23]
While migrating to this library, it's useful to have interop with Newtonsoft.

Provide a way to call the serialisation infrastructure through reflection for any given type, throwing a runtime exception if serialisation functions are unavailable.

**Comment by kolektiv** [comment]
I'll get this merged in soon, it's a good idea for people that might need it.

**Comment by kolektiv** [comment]
Is this still a thing? I'm not sure that branch ever built fully, but I'm still open to it if it can be completed sanely :)

**Comment by haf** [comment]
Nah, I've rid myself of Newtonsoft now and I'm really just scratching my own itches for this project. ;)

**Comment by kolektiv** [comment]
Hah, yes I've not gone near it for a while either. Same here really!

**Comment by kolektiv** [comment]
I think I'm going to close this one off as I've personally successfully avoided Newtonsoft for a long time, and I'm not sure there's enough call to resurrect this.
