### ISSUE TITLE
floats: -Infinity, +Infinity, NaN serialise funky

### ISSUE THREAD

**Issue by haf** [xyncro/chiron#28]
Consider how they should be handled; since they're not valid JSON, consider throwing an exception (partial function approach), or writing it as a string.

**Comment by kolektiv** [comment]
Hmmm. I think throwing is probably as sensible as anything in this case, as much as I dislike partial functions - better than silently losing fidelity I think...

**Comment by haf** [comment]
Ping?

**Comment by kolektiv** [comment]
Yeah, I think I'm happy with exception cases. Added to milestone...

**Comment by kolektiv** [comment]
https://github.com/kolektiv/chiron/commit/ad5bf47d25920ef5f1e469725e01b3d8a01b346e should include a fix for this.

**Comment by haf** [comment]
:+1:

**Comment by neoeinstein** [comment]
Before we release 8.0, we ought to add a similar validation to serializing `single` as well.

**Comment by kolektiv** [comment]
Hmmm, yes very true. I'll have a glance at that later.

**Comment by kolektiv** [comment]
Guard against this has gone in to 6.0.0-rc5 which I've just pushed. I'll close this off now as I think the basic scope is covered, and newer and shinier testing can produce newer and shinier bug reports... :)
