### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by gsscoder** [xyncro/chiron#40]
In your `README.md` you say:
> This is a fairly early work in progress, but usable enough to get feedback.

My feedback is that the library will benefit from adding even a minimal documentation, also some minimal sample(s) on `README.md` itself (or link to a blog post).

Otherwise code is well written and usable and fills the gap of Json functional style library.

Excellent work! :smile:

I've used it for [porting](https://github.com/gsscoder/YFinance.fs) an **Haskell** library dependent on [Data.Aeson](https://hackage.haskell.org/package/aeson-0.9.0.1/docs/Data-Aeson.html) to **F#**.

I don't like how I've [traversed](https://github.com/gsscoder/YFinance.fs/blob/master/src/YFinanceFs/Finance.fs#L46) Json AST, but I think that this can be enhanced and made clean using Lens (and it's not up to **Chiron** itself).

Thanks for sharing this project.

**Comment by kolektiv** [comment]
Oh that's very cool, thanks for telling me about it! As you say, the traversal code probably could be abstracted with lenses (Aether, perhaps, which works nicely with Chiron I hope) but it's great that it's helped you port Haskell code - I find myself doing similar things :)

You're totally right on the documentation. I've just got back from travelling for a week or two to refresh and recharge, and documentation and pleasant web presences is my first focus now I'm back with some energy - thanks for reminding me :) I'll be getting some simple and standard docs up soon Chiron, along with Aether, Hekate, etc...

Thanks again, it's always very cool to hear people actually finding things useful!

**Comment by gsscoder** [comment]
My pleasure! :smile:

It's true that **F#** is functional-first and multi-paradigm, but I'd like to see more _functional-first_ libs like yours.

So... Wellcome back to work! :+1:

**Comment by gsscoder** [comment]
I've followed your suggestion of traversing Json using partial lenses: https://github.com/gsscoder/YFinance.fs/blob/master/src/YFinanceFs/Finance.fs#L49.

Aether is really cool! (Just twitted about that...)

Thanks again for sharing it too. :+1: 

P.S.: I've a litte issue w/ Json null values -> I've opened issue #41.
