### ISSUE TITLE
Remove direct dependence on Aether

### ISSUE THREAD

**Issue by neoeinstein** [xyncro/chiron#68]
_Chiron_ will still provide _Aether_-compatible optics for consumption by others, but shouldn't directly depend on _Aether_ itself.

**Comment by kolektiv** [comment]
I think this is not a bad thing, but now i'm pondering things, what's the goal behind it? For `Json.Optic.*` to continue working we might need to duplicate a reasonable amount of Aether... I'm not against it, but we will retain an FParsec dependency - what's the driver for removing the Aether dependency?

**Comment by neoeinstein** [comment]
Yeah, we do still have that _FParsec_ dependency… Considering that, It may be best to throw this ticket away. My main motivation was to try to remove any extraneous dependencies with the goal of being more _Paket_ file-include friendly, but we still have other dependencies anyway. That may make this and #69 generally invalid.

**Comment by kolektiv** [comment]
Yeah - I think that probably makes this a lower priority - we're not realistically ever going to get to a dependency free single file, so one dependency versus two probably won't make much odds.

**Comment by panesofglass** [comment]
As it stands, Aether is still required in version 7, so I'm closing this for now. Please reopen if you feel it should be pursued further.
